# These are supported funding model platforms

github: ruchern-chong
patreon: ruchern_chong
open_collective: ruchern-chong
ko_fi: ruchern_chong
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # Replace with a single custom sponsorship URL
